demo/src/app.json, demo/src/pages/switch/switch.json, demo/src/pages/switch/switch.scss, demo/src/pages/switch/switch.ts, demo/src/pages/switch/switch.wxml, docs/src/doc.config.js, src/Switch/README.md, src/Switch/switch.json, src/Switch/switch.scss, src/Switch/switch.ts, src/Switch/switch.wxml
=> 【FEA】表单组件-Switch

dist/Icon/icon.wxss, packages/style/icons.less, src/style/icons.less
* Hardware:
* Toolchain:
* SDK version:
=> feat: update iconfont

src/EmptyPage/index.json, src/EmptyPage/index.ts, src/EmptyPage/index.wxml, src/EmptyPage/index.wxss
* Hardware:
* Toolchain:
* SDK version:
=> feat: 迁移EmptyPage到oak

package.json, packages/Loading/loading.less, packages/Loading/loading.ts, packages/Loading/loading.wxml, src/Loading/loading.less, src/Loading/loading.ts, src/Loading/loading.wxml
loading -icon  增加一个阴影 选项；增加mid尺寸；外部样式控制
=> Loading icon shadow

src/Image/image.wxml
* Hardware:
* Toolchain:
* SDK version:
=> feat: 图片优化

package.json
* Hardware:
* Toolchain:
* SDK version:
=> V7.7.0 image

package.json, src/Image/image.ts, src/Image/image.wxml
1. 有的场景只要使用低质量图片就可以满足需求
2. 有的图片组件不需要背景图片
=> V785 image modify

package.json, src/Label/label.less, src/Label/label.ts, src/Label/label.wxml
=> Label modify

package.json, src/Icon/icon.ts, src/Icon/icon.wxml, src/Image/image.ts, src/Image/image.wxml
* Hardware:
* Toolchain:
* SDK version:
=> Feature 6131 index tab

package.json, packages/style/icons.less, src/style/icons.less
=> feat: add icon

package.json
* Hardware:
* Toolchain:
* SDK version:
=> 7.11.5 promotion

.gitignore, __build__/gulpfile.babel.js, package.json, src/Stepper/stepper.ts, src/Stepper/stepper.wxml
=> Feature 6608 v7125 addcart animation

demo/src/app.json, demo/src/pages/index/index.wxml, demo/src/pages/onReachBottom/onReachBottom.json, demo/src/pages/onReachBottom/onReachBottom.less, demo/src/pages/onReachBottom/onReachBottom.ts, demo/src/pages/onReachBottom/onReachBottom.wxml, demo/src/pages/onReachBottomDemo/onReachBottomDemo.json, demo/src/pages/onReachBottomDemo/onReachBottomDemo.less, demo/src/pages/onReachBottomDemo/onReachBottomDemo.ts, demo/src/pages/onReachBottomDemo/onReachBottomDemo.wxml, docs/markdown/changelog.md, docs/src/doc.config.js, packages/OnReachBottom/README.md, packages/OnReachBottom/onReachBottom.json, packages/OnReachBottom/onReachBottom.less, packages/OnReachBottom/onReachBottom.ts, packages/OnReachBottom/onReachBottom.wxml, src/OnReachBottom/onReachBottom.json, src/OnReachBottom/onReachBottom.less, src/OnReachBottom/onReachBottom.ts, src/OnReachBottom/onReachBottom.wxml, src/OnReachBottom/variable.less, src/style/variable.less
* Hardware:
* Toolchain:
* SDK version:
=> 触底组件完成+demo也完成

demo/src/pages/slideview/slideview.ts, demo/src/pages/slideview/slideview.wxml, packages/SlideView/README.md, packages/SlideView/slide-view.less, packages/SlideView/slide-view.ts, packages/SlideView/slide-view.wxml, src/SlideView/README.md, src/SlideView/slide-view.less, src/SlideView/slide-view.ts, src/SlideView/slide-view.wxml
* Hardware:
* Toolchain:
* SDK version:
=> feat: 收藏需求支持

package.json, src/EmptyPage/index.ts, src/EmptyPage/index.wxml
=> Feature 9757 v830 SKU share

package.json
=> Feature 9497 v830 skudetail scroll

package.json, packages/Confirm/confirm.less, src/Confirm/confirm.less
* Hardware:
* Toolchain:
* SDK version:
=> Fix oak confirm

package.json, packages/Confirm/confirm.less, packages/EmptyPage/index.ts, packages/EmptyPage/index.wxml, packages/Toast/toast.js, packages/Toast/toast.wxml, src/Toast/toast.js, src/Toast/toast.wxml
* Hardware:
* Toolchain:
* SDK version:
=> Fix toast show

package.json, packages/Toast/toast.js, src/Toast/toast.js
* Hardware:
* Toolchain:
* SDK version:
=> feat: 优化 toast

package.json, packages/Toast/toast.js, src/Toast/toast.js
* Hardware:
* Toolchain:
* SDK version:
=> fix: toast关闭

package.json, src/Button/variable.less
* Hardware:
* Toolchain:
* SDK version:
=> fix: 修复button边框宽度问题

package.json, packages/Button/button.ts, src/Button/button.ts
* Hardware:
* Toolchain:
* SDK version:
=> fix: buttonGroup下只有一个按钮时，边框变直角问题修复

package.json, packages/Button/README.md, packages/Button/button.ts, src/Button/README.md, src/Button/button.ts
* Hardware:
* Toolchain:
* SDK version:
=> fix: oak-button兼容问题修复

demo/src/pages/image/index.wxml, package.json, src/Image/image.wxml
=> 修复w=0, 没有height

package.json
=> feat: 更新版本

package.json, src/GlobalLoading/index.less, src/GlobalLoading/index.wxml, src/Loading/loading.less, src/Loading/loading.wxml
=> feat: global loading修改

package.json, src/Image/image.wxml
=> feat: release撤销image修改

demo/src/pages/image/index.less, demo/src/pages/image/index.wxml, package.json, src/Image/image.wxml
=> Fix image width

package.json, src/style/icons.less
=> 极速客服icon更新

package.json, src/style/icons.less
=> Dev v885 kefu feature

demo/src/app.wxss, demo/src/pages/popup/popup.less, demo/src/pages/popup/popup.ts, demo/src/pages/popup/popup.wxml, package.json, src/ActionSheet/action-sheet.wxml, src/Dialog/dialog.wxml, src/Popup/README.md, src/Popup/popup.json, src/Popup/popup.less, src/Popup/popup.ts, src/Popup/popup.wxml, src/Popup/variable.less
=> 2.0.0 bate popup

package.json, src/style/icons.less
* Hardware:
* Toolchain:
* SDK version:
=> Oak 815 pingtuan
